Repository JesseMattson/PurrgentCare, pull requests merged in 2024-08, with the labels that each got.

#68 63 spike explore open source fake generator
  documentation/spikes/OpenSourceFakeDataGeneration.md
Labels: spike

#72 66-chore-use-repo-secrets-for-urls-in-pipeline
  .github/workflows/ci-cd.yml
  documentation/github-secrets.md
  makefile
Labels: chore

#73 57 feature configure UI testing
  .github/workflows/ci-cd.yml
  .github/workflows/ui-ci-cd.yml
  makefile
  purrgent-care-ui/package-lock.json
  purrgent-care-ui/package.json
  purrgent-care-ui/src/AccountEdit.js
  purrgent-care-ui/src/AccountEdit.test.js
  purrgent-care-ui/src/AccountList.js
  purrgent-care-ui/src/AccountList.test.js
  purrgent-care-ui/src/App.test.js
  purrgent-care-ui/src/Home.test.js
  purrgent-care-ui/src/PersonEdit.js
  purrgent-care-ui/src/PersonEdit.test.js
  purrgent-care-ui/src/PersonList.js
  purrgent-care-ui/src/PersonList.test.js
  purrgent-care-ui/src/PetEdit.js
  purrgent-care-ui/src/PetEdit.test.js
  purrgent-care-ui/src/PetList.js
  purrgent-care-ui/src/PetList.test.js
  purrgent-care-ui/src/index.test.js
Labels: feature
